# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "af0afba4158ffe367167317e1c13791b"
name = "qr-code-app"
handle = "qr-code-app-282"
application_url = "https://favorites-stolen-passengers-pins.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-e0570791.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://favorites-stolen-passengers-pins.trycloudflare.com/auth/callback",
  "https://favorites-stolen-passengers-pins.trycloudflare.com/auth/shopify/callback",
  "https://favorites-stolen-passengers-pins.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks"

[pos]
embedded = false
